name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: go-codeowners-windows-amd64
          path: |
            go-codeowners.exe
            config.yml

  build_linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: go-codeowners-linux-amd64
          path: |
            go-codeowners
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: arm64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: go-codeowners-linux-arm64
          path: |
            go-codeowners
            config.yml
        
  build_darwin:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: go-codeowners-darwin-amd64
          path: |
            go-codeowners
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: arm64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: go-codeowners-darwin-arm64
          path: |
            go-codeowners
            config.yml

      
