name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  goVersion: '1.23'

jobs:
  build:
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
        arch: [amd64, arm64]
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.goVersion }}
        
      - name: Test
        run: go test ./...
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOARCH: ${{ matrix.arch }}
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            go-codeowners
            go-codeowners.exe
